name: Clean Artifact Registry

on:
  workflow_dispatch:

env:
  PROJECT_ID: freenet-353920
  GAR_LOCATION: us-east1
  REPO_LOCATION: $GAR_LOCATION-docker.pkg.dev/freenet-repo
  IMAGE_PATH1: $REPO_LOCATION/freenet-org-production
  IMAGE_PATH2: $REPO_LOCATION/freenet-org-staging

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'


    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/516912345376/locations/global/workloadIdentityPools/freenetorg-pool/providers/github'
          service_account: 'gke-service-acct@freenet-353920.iam.gserviceaccount.com'

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

      - name: Clean Artifact Registry
        uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=$IMAGE_PATH1
            -repo=$IMAGE_PATH2
            -grace=24H
            -keep=3
            -dry_run=true
            
